tasks:
  - name: Install, Start Node and deploy
    init: yarn
    command: npx hardhat node
  - name: Deploy Smart Contract and start server
    command: |
      gp await-port 8545
      npx hardhat run scripts/deploy.js --network localhost
      npm run dev
    openMode: tab-after